spring:
  application:
    # This is the name of service
    name: timer-service
  h2:
    console:
     enabled: true
     path: /h2_console
  datasource:
    url: jdbc:h2:file:./pomodorotimer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
     ddl-auto: update
     use-new-id-generator-mappings: true
    show-sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    debug: true
server:
  port: 8080

---
spring:
  profiles: test
  h2:
    console:
     enabled: true
     path: /h2_console
  datasource:
    url: jdbc:h2:file:./pomodorotimertest;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
     ddl-auto: update
     use-new-id-generator-mappings: true
    show-sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    debug: true
server:
  port: 8080